replace `argonautica` with `rust-argon2`
Wulf/create-rust-app pull request #56
Opened 2022-10-12 19:11 UTC by XBagon

`argonautica` seems to be unmaintained for 3 years now and only supports the C-implementation. `rust-argon2` seems to be the go-to modern pure-rust implementation, so I tried to replace it bit for bit as well as I could.

2022-10-25 15:17 UTC, Wulf commented
hey @XBagon, thanks a lot for this PR -- I was actually going to look into this! Sorry for reviewing this so late, it's been a busy few weeks.

2022-10-25 19:07 UTC, Wulf requested changes
Just a minor comment, let me know what you think!

2022-11-03 13:48 UTC, XBagon commented on create-rust-app/src/auth/controller.rs
> +}
I personally have no problem with this change, just did some minor reasearch to understand which improvements that would bring for security, as it seems probably none.
https://stackoverflow.com/a/5197921

2022-11-07 03:25 UTC, Wulf commented on create-rust-app/src/auth/controller.rs
> +}
thanks for sharing @XBagon. I agree, after reading more about it, it seems to be almost negligible. Let's use 16 bytes as recommended in the [argon2 paper](https://raw.githubusercontent.com/P-H-C/phc-winner-argon2/master/argon2-specs.pdf).

![image](https://user-images.githubusercontent.com/4259838/200220089-b2114111-4b41-408f-b868-0a69d6878804.png)

2022-11-07 03:26 UTC, Wulf commented on create-rust-app/src/auth/controller.rs
> +}
Also, I also want to say sorry for dragging this out for long -- I had to make sure we did the right thing :)

2022-11-13 20:30 UTC, Wulf commented
I'm going to merge this to the `rust-argon2` branch and create a new PR (I can't figure out how to create a PR for your repo -- it says I already have the repository forked :sweat_smile:)

2022-11-13 20:30 UTC, merged

2022-11-14 04:09 UTC, XBagon commented
> I'm going to merge this to the `rust-argon2` branch and create a new PR (I can't figure out how to create a PR for your repo -- it says I already have the repository forked 😅)

Okay, sounds like weird behaviour..
Thanks for finishing it, didn't get around to do the small change 😅